import { NextResponse } from 'next/server';
import dbConnect from '@/lib/mongodb';
import Property from '@/models/Property';

const SAMPLE_PROPERTIES = [
  // --- PROMOTED PROPERTIES (10 Cards) ---
  {
    title: "The Oberoi Sky City",
    location: "Borivali East, Mumbai",
    city: "Mumbai",
    type: "residential",
    category: "Luxury Apartments",
    price: "₹4.5 Cr+",
    priceNumeric: 45000000,
    images: ["https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?q=80&w=1000&auto=format&fit=crop"],
    bedrooms: 3,
    bathrooms: 3,
    sqft: 1800,
    badge: "PROMOTED",
    agent: { name: "Sameer Khan", avatar: "https://randomuser.me/api/portraits/men/1.jpg", rating: 4.8, reviews: 120 },
    isFeatured: true,
    isPreLeased: false,
    isPromoted: true
  },
  {
    title: "Lodha World One",
    location: "Lower Parel, Mumbai",
    city: "Mumbai",
    type: "residential",
    category: "Ultra Luxury",
    price: "₹12.0 Cr+",
    priceNumeric: 120000000,
    images: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=1000&auto=format&fit=crop"],
    bedrooms: 4,
    bathrooms: 5,
    sqft: 3200,
    badge: "EXCLUSIVE",
    agent: { name: "Anjali Mehta", avatar: "https://randomuser.me/api/portraits/women/2.jpg", rating: 4.9, reviews: 85 },
    isFeatured: true,
    isPreLeased: false,
    isPromoted: true
  },
  {
    title: "Piramal Aranya",
    location: "Byculla, Mumbai",
    city: "Mumbai",
    type: "residential",
    category: "High-end Living",
    price: "₹7.2 Cr+",
    priceNumeric: 72000000,
    images: ["https://images.unsplash.com/photo-1512918728675-ed5a9ecde9d7?q=80&w=1000&auto=format&fit=crop"],
    bedrooms: 3,
    bathrooms: 4,
    sqft: 2100,
    badge: "HOT DEAL",
    agent: { name: "Rohan Das", avatar: "https://randomuser.me/api/portraits/men/3.jpg", rating: 4.7, reviews: 60 },
    isFeatured: true,
    isPreLeased: false,
    isPromoted: true
  },
  {
    title: "Godrej Meridien",
    location: "Sector 106, Gurgaon",
    city: "Gurgaon",
    type: "residential",
    category: "Lifestyle Apartments",
    price: "₹3.8 Cr+",
    priceNumeric: 38000000,
    images: ["https://images.unsplash.com/photo-1613490493576-7fde63acd811?q=80&w=1000&auto=format&fit=crop"],
    bedrooms: 3,
    bathrooms: 3,
    sqft: 2000,
    badge: "PROMOTED",
    agent: { name: "Karan Johar", avatar: "https://randomuser.me/api/portraits/men/4.jpg", rating: 4.6, reviews: 45 },
    isFeatured: true,
    isPreLeased: false,
    isPromoted: true
  },
  {
    title: "DLF The Aralias",
    location: "Golf Course Rd, Gurgaon",
    city: "Gurgaon",
    type: "residential",
    category: "Luxury Condos",
    price: "₹25.0 Cr+",
    priceNumeric: 250000000,
    images: ["https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?q=80&w=1000&auto=format&fit=crop"],
    bedrooms: 5,
    bathrooms: 6,
    sqft: 6000,
    badge: "VVIP",
    agent: { name: "Sonia Gandhi", avatar: "https://randomuser.me/api/portraits/women/5.jpg", rating: 5.0, reviews: 210 },
    isFeatured: true,
    isPreLeased: false,
    isPromoted: true
  },
  {
    title: "Sobha Windsor",
    location: "Whitefield, Bangalore",
    city: "Bangalore",
    type: "residential",
    category: "Signature Homes",
    price: "₹2.5 Cr+",
    priceNumeric: 25000000,
    images: ["https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?q=80&w=1000&auto=format&fit=crop"],
    bedrooms: 3,
    bathrooms: 3,
    sqft: 1900,
    badge: "NEW LAUNCH",
    agent: { name: "Ravi Teja", avatar: "https://randomuser.me/api/portraits/men/6.jpg", rating: 4.5, reviews: 30 },
    isFeatured: true,
    isPreLeased: false,
    isPromoted: true
  },
  {
    title: "Prestige Kingfisher",
    location: "Lavelle Rd, Bangalore",
    city: "Bangalore",
    type: "residential",
    category: "Luxury Mansions",
    price: "₹35.0 Cr+",
    priceNumeric: 350000000,
    images: ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1000&auto=format&fit=crop"],
    bedrooms: 6,
    bathrooms: 7,
    sqft: 8000,
    badge: "ELITE",
    agent: { name: "Vijay Mallya", avatar: "https://randomuser.me/api/portraits/men/7.jpg", rating: 4.9, reviews: 50 },
    isFeatured: true,
    isPreLeased: false,
    isPromoted: true
  },
  {
    title: "Brigade Gateway",
    location: "Rajajinagar, Bangalore",
    city: "Bangalore",
    type: "commercial",
    category: "IT Office",
    price: "₹15.0 Cr+",
    priceNumeric: 150000000,
    images: ["https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=1000&auto=format&fit=crop"],
    sqft: 15000,
    tenantBrand: "Amazon India",
    leaseTerm: "10 Years",
    roi: "7.5%",
    badge: "PROMOTED",
    agent: { name: "Nitin Kamath", avatar: "https://randomuser.me/api/portraits/men/8.jpg", rating: 4.8, reviews: 75 },
    isFeatured: true,
    isPreLeased: true,
    isPromoted: true
  },
  {
    title: "M3M International Financial Center",
    location: "Sector 66, Gurgaon",
    city: "Gurgaon",
    type: "commercial",
    category: "Grade A Office",
    price: "₹5.5 Cr+",
    priceNumeric: 55000000,
    images: ["https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=1000&auto=format&fit=crop"],
    sqft: 5000,
    tenantBrand: "Google Cloud",
    leaseTerm: "9 Years",
    roi: "8.1%",
    badge: "INVESTMENT READY",
    agent: { name: "Pankaj Advani", avatar: "https://randomuser.me/api/portraits/men/9.jpg", rating: 4.7, reviews: 90 },
    isFeatured: true,
    isPreLeased: true,
    isPromoted: true
  },
  {
    title: "Kalpataru Radiance",
    location: "Goregaon West, Mumbai",
    city: "Mumbai",
    type: "residential",
    category: "Smart Homes",
    price: "₹3.2 Cr+",
    priceNumeric: 32000000,
    images: ["https://images.unsplash.com/photo-1560448204-61dc36dc98c8?q=80&w=1000&auto=format&fit=crop"],
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1200,
    badge: "BEST VALUE",
    agent: { name: "Tina Dabi", avatar: "https://randomuser.me/api/portraits/women/10.jpg", rating: 4.6, reviews: 40 },
    isFeatured: true,
    isPreLeased: false,
    isPromoted: true
  },

  // --- AVERAGE PROPERTIES (10 Cards) ---
  {
    title: "Green Valley Residency",
    location: "Thane West, Mumbai",
    city: "Mumbai",
    type: "residential",
    category: "Apartments",
    price: "₹1.1 Cr+",
    priceNumeric: 11000000,
    images: ["https://images.unsplash.com/photo-1493397665643-c5fab07a53ba?q=80&w=1000&auto=format&fit=crop"],
    bedrooms: 2,
    bathrooms: 2,
    sqft: 950,
    agent: { name: "Aman Gupta", avatar: "https://randomuser.me/api/portraits/men/11.jpg", rating: 4.2, reviews: 20 },
    isFeatured: false,
    isPreLeased: false,
    isPromoted: false
  },
  {
    title: "Urban Nest",
    location: "Hadapsar, Pune",
    city: "Pune",
    type: "residential",
    category: "Apartments",
    price: "₹85 Lacs+",
    priceNumeric: 8500000,
    images: ["https://images.unsplash.com/photo-1459767129954-151cb74e5080?q=80&w=1000&auto=format&fit=crop"],
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1050,
    agent: { name: "Sneha Patil", avatar: "https://randomuser.me/api/portraits/women/12.jpg", rating: 4.1, reviews: 15 },
    isFeatured: false,
    isPreLeased: false,
    isPromoted: false
  },
  {
    title: "Skyline Heights",
    location: "Hitech City, Hyderabad",
    city: "Hyderabad",
    type: "residential",
    category: "Apartments",
    price: "₹1.8 Cr+",
    priceNumeric: 18000000,
    images: ["https://images.unsplash.com/photo-1460317442991-0ec209397118?q=80&w=1000&auto=format&fit=crop"],
    bedrooms: 3,
    bathrooms: 3,
    sqft: 1600,
    agent: { name: "Rahul Reddy", avatar: "https://randomuser.me/api/portraits/men/13.jpg", rating: 4.3, reviews: 25 },
    isFeatured: false,
    isPreLeased: false,
    isPromoted: false
  },
  {
    title: "Sunrise Villas",
    location: "Kanakapura Rd, Bangalore",
    city: "Bangalore",
    type: "residential",
    category: "Villas",
    price: "₹4.2 Cr+",
    priceNumeric: 42000000,
    images: ["https://images.unsplash.com/photo-1613490493576-7fde63acd811?q=80&w=1000&auto=format&fit=crop"],
    bedrooms: 4,
    bathrooms: 4,
    sqft: 2800,
    agent: { name: "Deepak Chahar", avatar: "https://randomuser.me/api/portraits/men/14.jpg", rating: 4.4, reviews: 30 },
    isFeatured: false,
    isPreLeased: false,
    isPromoted: false
  },
  {
    title: "Metro Plaza",
    location: "Noida Sector 18",
    city: "Noida",
    type: "commercial",
    category: "Retail Shops",
    price: "₹2.2 Cr+",
    priceNumeric: 22000000,
    images: ["https://images.unsplash.com/photo-1441986300917-64674bd600d8?q=80&w=1000&auto=format&fit=crop"],
    sqft: 800,
    agent: { name: "Kapil Sharma", avatar: "https://randomuser.me/api/portraits/men/15.jpg", rating: 4.0, reviews: 10 },
    isFeatured: false,
    isPreLeased: false,
    isPromoted: false
  },
  {
    title: "Woodland Retreat",
    location: "Shimla, HP",
    city: "Shimla",
    type: "residential",
    category: "Cottages",
    price: "₹2.8 Cr+",
    priceNumeric: 28000000,
    images: ["https://images.unsplash.com/photo-1449156001931-828320445d4e?q=80&w=1000&auto=format&fit=crop"],
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1500,
    agent: { name: "Priya Thakur", avatar: "https://randomuser.me/api/portraits/women/16.jpg", rating: 4.5, reviews: 18 },
    isFeatured: false,
    isPreLeased: false,
    isPromoted: false
  },
  {
    title: "Harbor View",
    location: "Colaba, Mumbai",
    city: "Mumbai",
    type: "residential",
    category: "Apartments",
    price: "₹18.0 Cr+",
    priceNumeric: 180000000,
    images: ["https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?q=80&w=1000&auto=format&fit=crop"],
    bedrooms: 4,
    bathrooms: 4,
    sqft: 3000,
    agent: { name: "Akshay Kumar", avatar: "https://randomuser.me/api/portraits/men/17.jpg", rating: 4.9, reviews: 55 },
    isFeatured: false,
    isPreLeased: false,
    isPromoted: false
  },
  {
    title: "Corporate Center",
    location: "Electronic City, Bangalore",
    city: "Bangalore",
    type: "commercial",
    category: "Office Space",
    price: "₹8.0 Cr+",
    priceNumeric: 80000000,
    images: ["https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=1000&auto=format&fit=crop"],
    sqft: 10000,
    agent: { name: "Sunil Shetty", avatar: "https://randomuser.me/api/portraits/men/18.jpg", rating: 4.6, reviews: 22 },
    isFeatured: false,
    isPreLeased: false,
    isPromoted: false
  },
  {
    title: "Park Avenue",
    location: "New Town, Kolkata",
    city: "Kolkata",
    type: "residential",
    category: "Apartments",
    price: "₹75 Lacs+",
    priceNumeric: 7500000,
    images: ["https://images.unsplash.com/photo-1460317442991-0ec209397118?q=80&w=1000&auto=format&fit=crop"],
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1100,
    agent: { name: "Abhijit Ghosh", avatar: "https://randomuser.me/api/portraits/men/19.jpg", rating: 4.1, reviews: 12 },
    isFeatured: false,
    isPreLeased: false,
    isPromoted: false
  },
  {
    title: "Lakeside Residences",
    location: "Gachibowli, Hyderabad",
    city: "Hyderabad",
    type: "residential",
    category: "High-rise",
    price: "₹2.5 Cr+",
    priceNumeric: 25000000,
    images: ["https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?q=80&w=1000&auto=format&fit=crop"],
    bedrooms: 3,
    bathrooms: 3,
    sqft: 1850,
    agent: { name: "Srinivas Rao", avatar: "https://randomuser.me/api/portraits/men/20.jpg", rating: 4.4, reviews: 28 },
    isFeatured: false,
    isPreLeased: false,
    isPromoted: false
  }
];

export async function POST() {
  try {
    await dbConnect();
    await Property.deleteMany({}); // Clear existing
    await Property.insertMany(SAMPLE_PROPERTIES);
    return NextResponse.json({ message: "Database seeded with 20 properties (10 Promoted + 10 Average) successfully" }, { status: 200 });
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
